# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Wolfie!!
tagline:             'Hello, Shittie'
description:         'I am <a href="http://jekyllrb.com" target="_blank">Wolfie</a> You will like <a href="https://twitter.com/mdo" target="_blank">me</a>.'
url:                 aileen365.github.io/wolfie
baseurl:             /wolfie/
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
