# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:        pretty

# Setup
title:               Wolfie
tagline:             'A Jekyll theme'
description:         'Test2'
url:                 aileen365.github.io/lanyon
baseurl:             /
#paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             aileen365@gmail.com

# Custom vars
version:             1.0.0
